---
name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: iamsauravsharma/create-dotenv@v4.0.0
        with:
          file-path: '/tmp/.env'
        env:
          GITHUB_TOKEN: ${{ secrets.STUDIO_GITHUB_TOKEN }}
      - uses: cliffano/command-docker-action@main
        with:
          command: 'make ci'
          image: cliffano/studio:2.16.0
          extra_path: '/root/.local/bin:/root/go/bin:/usr/local/go/bin:/usr/local/node/bin'
          shell: bash
          env_file: '/tmp/.env'
